version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
  be:
    build:
      context: .
      dockerfile: Dockerfile-be
    ports:
      - "5000:5000"
    depends_on:
      - db

  fe:
    build:
      context: .
      dockerfile: Dockerfile-fe
    ports:
      - "3000:3000"
    depends_on:
      - be