version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ansible
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      docker-net:
        ipv4_address: 192.168.0.2
    hostname: db

  be:
    build:
      context: .
      dockerfile: Dockerfile-be
    ports:
      - "5000:5000"
    volumes:
      - ./be-data:/home/node
    depends_on:
      - db
    networks:
      docker-net:
        ipv4_address: 192.168.0.3
    hostname: be

  fe:
    build:
      context: .
      dockerfile: Dockerfile-fe
    ports:
      - "3000:3000"
    volumes:
      - ./fe-data:/home/node/ansible-fe
    depends_on:
      - be
    networks:
      docker-net:
        ipv4_address: 192.168.0.4
    hostname: fe

networks:
  docker-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  db-data:
  be-data:
  fe-data: