version: '2.29.2'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    networks:
      docker-net:
        ipv4_address: 192.168.0.2
    hostname: db
    volumes:
      - ./db:/var/lib/postgresql/data

  be:
    build:
      context: .
      dockerfile: Dockerfile-be
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      docker-net:
        ipv4_address: 192.168.0.3
    hostname: be
    container_name: be
    volumes:
      - ./be/server.js:/home/node/server.js

  fe:
    build:
      context: .
      dockerfile: Dockerfile-fe
    ports:
      - "3000:3000"
    depends_on:
      - be
    networks:
      docker-net:
        ipv4_address: 192.168.0.4
    hostname: fe
    container_name: fe
    volumes:
      - ./fe/src:/home/node/src

networks:
  docker-net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.0.0/24

volumes:
  db:
  be:
  fe:
