# Use the official Node.js image as a base
FROM node:latest

# Update and install necessary packages
RUN apt update && \
    apt install -y nano net-tools iputils-ping curl tmux 

# Set the working directory
WORKDIR /home/node

# Install Express
RUN npx --yes create-react-app ansible-fe
WORKDIR /home/node/ansible-fe

RUN git clone https://github.com/hakidon/Ansible-testbed.git

RUN rm -r src && mv Ansible-testbed/fe/src .
RUN rm -r Ansible-testbed

EXPOSE 3000

CMD ["npm", "start"]