FROM node:latest

RUN apt update && \
    apt install -y nano net-tools iputils-ping curl tmux postgresql-client python3-paramiko python3-pip python3.11-venv

WORKDIR /home/node

RUN git clone https://github.com/hakidon/Ansible-testbed.git

RUN cat Ansible-testbed/be/ansible/config/ssh-config  /etc/ssh/ssh_config
RUN mv Ansible-testbed/be/ansible/config/ansible-config  ~/.ansible.cfg
RUN mv Ansible-testbed/be/server.js  .
RUN mkdir -p ansible && mv Ansible-testbed/be/ansible  .
RUN rm -r Ansible-testbed

RUN python3 -m venv python-venv
RUN /bin/bash -c "source python-venv/bin/activate && pip install ansible pyats genie psycopg2"

RUN npm install -g nodemon && \
    npm install express pg cors

EXPOSE 5000

CMD ["/bin/bash", "-c", "source python-venv/bin/activate && nodemon server.js"]

