---
- hosts: cisco_ios
  roles:
    - ansible-pyats
  tasks:
    - name: Run a command and get structured output
      pyats_parse_command:
        command: show ip route
      register: output

    - debug:
        var: output.structured