# Use the official Node.js image as a base
FROM node:latest

# Update and install necessary packages
RUN apt update && \
    apt install -y nano net-tools iputils-ping curl tmux postgresql-client python3-paramiko python3-pip python3.11-venv

# Set the working directory
WORKDIR /home/node

# Download and append to ssh-config
RUN curl "https://raw.githubusercontent.com/hakidon/Ansible-testbed/refs/heads/main/be/ansible/config/ssh-config" >> /etc/ssh/ssh_config
RUN curl -o ~/.ansible.cfg "https://raw.githubusercontent.com/hakidon/Ansible-testbed/refs/heads/main/be/ansible/config/ansible-config"

# Install Express
RUN npm install -g nodemon && \
    npm install express pg cors


RUN curl -o server.js "https://raw.githubusercontent.com/hakidon/Ansible-testbed/refs/heads/main/be/server.js"

# Create ansible directory and download files
RUN mkdir -p ansible && \
    curl -o ansible/inventory "https://raw.githubusercontent.com/hakidon/Ansible-testbed/refs/heads/main/ansible/inventory" && \
    curl -o ansible/info_ios.yml "https://raw.githubusercontent.com/hakidon/Ansible-testbed/refs/heads/main/ansible/info_ios.yml" && \
    git clone https://github.com/CiscoDevNet/ansible-pyats.git ansible/roles/ansible-pyats && \
    apt-get update && \
    python3 -m venv python-venv && \
    /bin/bash -c "source python-venv/bin/activate && pip install ansible pyats genie psycopg2"

# Get custom parser
RUN mkdir -p ansible/custom-parser/library/ && \
    curl -o ansible/custom-parser/library/custom_parse_command.py "https://raw.githubusercontent.com/hakidon/Ansible-testbed/refs/heads/main/ansible/custom-parser/library/custom_parse_command.py"

EXPOSE 5000

CMD ["/bin/bash", "-c", "source python-venv/bin/activate && nodemon server.js"]

